// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// $ yarn run build
// running the above helps recompile the controllers

import { application } from "./application"

import FocusController from "./focus_controller"
application.register("focus", FocusController)
